config/routes.rb
Rails.application.routes.draw do
  get 'requests/new'

  get 'request/new'

  #get 'sessions/new'

  resources :users
  #get 'blogs/new'

  root 'initial_page#home'
  get '/home',  to: 'initial_page#home'
  get '/contact',  to: 'initial_page#contact'
  get '/admin',  to: 'initial_page#admin'
  #get '/post/:id',   to: 'blogs#post'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/admin', to: 'blogs#new'
  get   '/admin',   to: 'blogs#index'
  post    '/admin', to: 'blogs#create'
  get   '/request',  to: 'requests#new'
  post  '/request',  to: 'requests#create'
  delete '/requests/:id/edit', to: 'requests#destroy'
  delete '/blogs/:id/edit', to: 'blogs#destroy'
  #get   '/profile',  to: 'users#edit'
  #patch   '/profile', to: 'users#update'
  #get   '/blogs', to: 'blogs#index'

  resources :blogs
  resources :requests

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/initial_page_controller.rb
class InitialPageController < ApplicationController
  def home
    @blogs = Blog.all
  end

  def contact
  end

  def admin
    @requests = Request.all
    @blogs = Blog.all
  end


  def editBlog
    @blog = Blog.find(params[:blog_id])
  end

  def goHome
    redirect_to root_path
  end

  helper_method :goHome

end

app/helpers/initial_page_helper.rb
module InitialPageHelper
end

app/views/initial_page/admin.html.erb
<!--
#
# This is the HTML file for the "Admin" page.
# This contains the HTML for "User Requests" tab,
# Which displays info for any requests users have submitted.
# The HTML for the "New Posts" tab is rendered from app/views/blogs/new.html.erb
#
-->
<% provide(:title, "Admin") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Bochitto Travel</title>
  </head>
  <% if admin? %>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">

      <div style=" font-size: xx-large; margin-top: 3%;text-align: -webkit-center; " >
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist" style="width: 600px;">

          <li class="nav-item">
           <a style="height: 55px;font-size: smaller;" class="nav-link active" id="pills-hotel-tab" data-toggle="pill" href="#pills-hotel" role="tab" aria-controls="pills-contact" aria-selected="true">New Post</a>
          </li>

          <li class="nav-item">
            <a style="height: 55px;font-size: smaller;" class="nav-link " id="pills-cruise-tab" data-toggle="pill" href="#pills-cruise" role="tab" aria-controls="pills-contact" aria-selected="false">User Requests</a>
          </li>

          <li class="nav-item">
            <a style="height: 55px;font-size: smaller;" class="nav-link " id="pills-cruise-tab" data-toggle="pill" href="#pills-packages" role="tab" aria-controls="pills-contact" aria-selected="false">Blogs Posted</a>
          </li>
        </ul>
      </div>

    </div>

    <hr style=" color: navy;" >


    <div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-hotel" role="tabpanel" aria-labelledby="pills-hotel-tab">


<!-- NEW POSTS -->
<%= render :file => '/blogs/new' %>


<!-- USER REQUEST -->
<div class="tab-pane fade" id="pills-cruise" role="tabpanel" aria-labelledby="pills-cruise-tab">

  <table class="table" style="width:90%; margin:auto;">
   <thead class="thead-dark">
     <tr>
       <th scope="col">Email</th>
       <th scope="col">Origin</th>
       <th scope="col">Destination</th>
       <th scope="col">Start Date</th>
       <th scope="col">End Date</th>
       <th scope="col">Overall Price</th>
       <th scope="col"># Adults</th>
       <th scope="col"># Children</th>
       <th scope="col">Overall Details</th>
       <th scope="col">Notes</th>
       <th scope="col">Delete</th>
     </tr>
   </thead>
   <tbody>
     <% @requests.each do |request| %>
     <tr>
       <td><%= request.userName %></td>
       <td><%= request.origin %></td>
       <td><%= request.destination %></td>
       <td><%= request.startDate %></td>
       <td><%= request.endDate %></td>
       <td><%= request.overallPrice %></td>
       <td><%= request.numberAdults %></td>
       <td><%= request.numberChildren %></td>
       <td><%= request.overallDetails %></td>
       <td><%= request.notes %></td>
       <td><%= button_to "DELETE",  edit_request_path(request), method: :delete %></td>
     </tr>
     <% end %>
   </tbody>
  </table>

</div>
<!-- Blogs-->
  <div class="tab-pane fade" id="pills-packages" role="tabpanel" aria-labelledby="pills-packages-tab">
    <table class="table" style="width:90%; margin:auto;">
     <thead class="thead-dark">
       <tr>
         <th scope="col">Name</th>
         <th scope="col">Origin</th>
         <th scope="col">Destination</th>
         <th scope="col">Start Date</th>
         <th scope="col">End Date</th>
         <th scope="col">Overall Price</th>
         <th scope="col">Notes</th>
         <th scope="col">Delete</th>
       </tr>
     </thead>
     <tbody>
       <% @blogs.each do |blog| %>
       <tr>
         <td><%= blog.name %></td>
         <td><%= blog.origin %></td>
         <td><%= blog.destination %></td>
         <td><%= blog.startDate %></td>
         <td><%= blog.endDate %></td>
         <td><%= blog.overallPrice %></td>
         <td><%= blog.notes %></td>
         <td><%= button_to "DELETE",  edit_blog_path(blog), method: :delete %></td>
       </tr>
       <% end %>
     </tbody>
    </table>
  </div>
</div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <% else %>
    <% goHome %>
  <% end %>
  </body>
</html>

app/views/initial_page/contact.html.erb
<!--
#
# This is the HTML file for the "About Us" page
#
-->

<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
  <head>

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  	<link href="https://fonts.googleapis.com/css?family=Cormorant|Cormorant+Infant:400,600|Cormorant+Upright|Roboto" rel="stylesheet">

    <title><%= yield(:title) %> | Bochitto Travel</title>

  </head>

  <body>

    <%= render 'layouts/header' %>

    <div>
      	<%=  image_tag "logo10.png", class:"About_us_image" %>
    </div>

    <div class="container">
  <div class="row">
  <div class="column" >
    <h2 class="h2_about_us" >Why Bochitto Travel</h2>
    <p class="p_about_us">We specialize in making sure you have your dream trip met. Whether it is a cruise to the bahamas or a flight around the world, We will make sure all of your needs are met.</p>
  </div>

  <div class="column">
    <h2 class="h2_about_us" >Company History</h2>
    <p class="p_about_us">We are a local company from Gainesville, Florida Founded in March 2016. OUr main focus has been meeting group, family, or business travel needs. </p>
  </div>
</div>
</div>

<hr class="style-four">

<div class="container" style="margin-top: 4%;">

  <h1 class="h2_about_us" style="border-bottom: 0px">Who is Bochitto Travel</h2>

  	    <p class="p_about_us">Loving mother and daughter who loves to help others fulfill their dream to travel and see all the beauty and majesty that the world has to offer.</p>

</div>




<%= render 'layouts/footer' %>
  </body>

</html>

app/views/initial_page/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | Bochitto Travel</title>
<script type="text/javascript" src ="/assests/AP.js"></script>
<link rel="stylesheet" type="text/css" href="/assests/AP.css" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!--<link rel="shortcut icon" href="file:///C:/Users/Stalim/Downloads/favicon%20(6).ico" /> -->


<!-- semantic -->

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<src="https://code.jquery.com/jquery-3.1.1.min.js crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>


<title>Travel-Business</title>

</head>

<style type="text/css">
    .wrapper7 {
        text-align: center;
    }
    .wrapper7 ul {
        display: inline-block;
        margin: 0;
        padding: 0;
        /* For IE, the outcast */
        zoom:1;
        *display: inline;
    }
    .wrapper7 li {
        float: left;
        padding: 2px 5px;
        
    }
</style>




<body >
  <%= render 'layouts/header' %>
  <!-- hello koby  -->

<!--
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">< %= image_tag "final.png" %></a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <button id="Login" type="button" class="btn btn-outline-primary"><i class="fas fa-user-plus"> Login</i></button>
   		<button type="button" class="btn btn-outline-primary"><i class="fas fa-user"></i> Signup</button>
   	    </form>
  </div>
</nav> -->
<!-- <div><h1><i class="fab fa-twitter"></i></h1></div>

	<i class="fas fa-user-plus"></i>
	<i class="fas fa-user"></i>

<span class="icons"><i class="fab fa-instagram"></i></span> -->

<div id="mainImage" class="cf">




  <img class="bottom"  src="https://disneyparksmomspanel.disney.go.com/Content/images/QImages/ab1dd622-b2e2-43c0-a180-c8d7703f89ac.jpg" />
  <img  class="top"src="https://scontent-mia3-2.xx.fbcdn.net/v/t1.0-9/53155069_2235813123300317_3821106483400015872_o.jpg?_nc_cat=106&_nc_ht=scontent-mia3-2.xx&oh=7823ff1c971b9756644713d41fc4daa9&oe=5D1AB4B1">


<div>
<ul id="test" class="wrapper">
  <a href="http://www.google.com"><i class="fab fa-3x fa-instagram"></i></a>
  <a href="https://www.facebook.com/Travelgal68/"><i class="fab fa-3x fa-facebook-square"></i></a>
  <a href="http://www.twitter.com"><i class="fab fa-3x fa-twitter-square"></i></a>

</ul>
</div>

<div class="container" style="padding-top: 5%">
  <div id="jumbtr1" class="jumbotron jumbotron-fluid">
    <div class="container">
      <div class="align-items-center" style="margin-top: 20px;">
        <h1 class="typestyleall">
          Welcome to Bochitto Travel, where you can
          <span class="typewrite typestyle" data-period="1500" data-type='[ "create.", "adventure.", "plan.", "explore.", "travel." ]'></span>
        </h1>
      </div>
    </div>
  </div>
  	<!--<div style="position: sticky;"class="button_cont" align="center"><a class="example_c" href="add-website-here" target="_blank" rel="nofollow noopener">Request a trip</a></div> -->

    <div style="position: sticky;"class="button_cont" align="center">
      <% if logged_in? %>
      <%= link_to "Request a Trip", request_path, class: 'example_c' %>
      <% else %>
      <%= link_to "Log in to Request a Trip", login_path, class: 'example_c' %>
      <% end %>
    </div>
  </div>
</div>

<hr>


<!-- NAV WITH PACKAGES , HOTELS , CRUISES -->

<div style="  background: aliceblue;"> 

<div class="row" style=" background: #638cd7;" >  
<div class="wrapper7 col-sm-12 col-md-10 col-xl-12">
  <ul class="nav nav-tabs1" id="myTab" role="tablist" style=" font-size: x-large; height: 47px;" >

          <li class="nav-item1" style=" width: 200px;">
            <a style="  color:white;" class="nav-link active1" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><i class="fas fa-suitcase" style="margin-right: 10px;"></i>Packages</a>
          </li>
          <li class="nav-item1" style=" width: 200px;">
            <a style="  color:white;"class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><i class="fas fa-concierge-bell" style="margin-right: 10px;"></i>Hotels</a>
          </li>
          <li class="nav-item1"style=" width: 200px;">
            <a style="  color:white;"class="nav-link " id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false"><i class="fas fa-ship" style="margin-right: 10px"></i>Cruises</a>
          </li>
  </ul>
</div>
</div>


<!-- POSTS MAIN TAB -->


<div class=" container tab-content " id="myTabContent">

  <!-- PACKAGES -->
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab" style=" text-align: -webkit-center;" >

    <div style="display: unset;width: 100%">

      <% @blogs.each do |blog| %>
      <div id="post" class="card">
        <%= link_to blog_path(blog) do %>
        <% if ((blog.image_url == "") || (blog.image_url == nil)) %>
        <img class="card-img-top" src="https://www.incimages.com/uploaded_files/image/work-vacation-policy-pop_3122.jpg" style="width:100%; height: 180px">
        <% else %>
        <%= image_tag blog.image_url, style: "width:100%; height: 180px" %>
        <% end %>
        <div id="info" class="card-body">
          <h4 class="card-title"><%= blog.destination %></h4>
          <p class="card-text"></p>
          <h3>From $<%= blog.overallPrice %></h3>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>

  </div>
  <!-- HOTEL -->

  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab" style=" text-align: -webkit-center;">

    <div style="display: unset;width: 100%">
      <% @blogs.where(:name => "Hotel").each do |blog| %>
      <div id="post" class="card">
        <%= link_to blog_path(blog) do %>
        <% if ((blog.image_url == "") || (blog.image_url == nil)) %>
        <img class="card-img-top" src="https://www.incimages.com/uploaded_files/image/work-vacation-policy-pop_3122.jpg" style="width:100%; height: 180px">
        <% else %>
        <%= image_tag blog.image_url, style: "width:100%; height: 180px" %>
        <% end %>
        <div id="info" class="card-body">
          <h4 style="background: #0077dda6" class="card-title"><%= blog.destination %></h4>
          <p class="card-text"></p>
          <h3 style="background: #0077dda6">From $<%= blog.overallPrice %></h3>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>


  <!-- CRUISES -->
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab" style=" text-align: -webkit-center;">
    <div style="display: unset;width: 100%">
      <% @blogs.where(:name => "Cruise").each do |blog| %>
      <div id="post" class="card" >
        <%= link_to blog_path(blog) do %>
        <% if ((blog.image_url == "") || (blog.image_url == nil)) %>
        <img class="card-img-top" src="https://www.incimages.com/uploaded_files/image/work-vacation-policy-pop_3122.jpg" style="width:100%; height: 180px">
        <% else %>
        <%= image_tag blog.image_url, style: "width:100%; height: 180px" %>
        <% end %>
        <div id="info" class="card-body">
          <h4 class="card-title" style="background: #67b691c2"><%= blog.destination %></h4>
          <p class="card-text"></p>
          <h3 style="background: #67b691c2">From $<%= blog.overallPrice %></h3>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>

  </div>

</div>

<!--
  <div id="post" class="card" >
    <div alt="Card image">
      < %= link_to post_path do %>
        < %= image_tag 'https://www.incimages.com/uploaded_files/image/work-vacation-policy-pop_3122.jpg', :class => "style_image card-img-top" %>
      <div id="info" class="card-body">
        <h4 class="card-title">Varadero</h4>
        <p class="card-text"></p>
        <h3>From $299</h3>
      </div>
      < % end %>
    </div>
  </div>

   <div id="post" class="card" >
    <img class="card-img-top" src="https://cdn7.dissolve.com/p/D1028_94_065/D1028_94_065_1200.jpg" style="width:100%;height: 180px">
    <div id="info" class="card-body">
      <h4 class="card-title">New York</h4>
      <p class="card-text"></p>
      <h3 >From $99</h3>
    </div>
  </div>

   <div id="post" class="card" >
    <img class="card-img-top" src="https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/02/22/09/paris.jpg?w968h681" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://www.trilussapalacehotel.it/wp-content/uploads/2018/01/roma-colosseo.jpg" style="width:100%; height: 180px">
    <img class="card-img-top" src="http://www.ricardobofill.es/wp-content/uploads//2016/03/W_Barcelona_Hotel_Ricardo_Bofill_Taller_Arquitectura_Barcelona_Spain_01.jpg" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/commons/5/5e/Australia_Day.jpg" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://pix10.agoda.net/hotelImages/336/336870/336870_16042115000041680438.jpg?s=1024x768" alt="Card image" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://www.gannett-cdn.com/-mm-/1abbac059a7e6f21ff3aa7e38760a41a48819119/c=0-217-2118-1414/local/-/media/2018/04/14/USATODAY/USATODAY/636592630826477551-GettyImages-813272528.jpg?width=3200&height=1680&fit=crop" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://www.worldtravelguide.net/wp-content/uploads/2017/09/shu-Europe-Spain-Madrid-Financial-district-245037493-Sean-Pavone-1440x823.jpg" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://www.incimages.com/uploaded_files/image/work-vacation-policy-pop_3122.jpg" alt="Card image" style="width:100%;height: 180px">
    <img class="card-img-top" src="https://cdn7.dissolve.com/p/D1028_94_065/D1028_94_065_1200.jpg" style="width:100%;height: 180px">
    <img class="card-img-top" src="https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/02/22/09/paris.jpg?w968h681" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://www.trilussapalacehotel.it/wp-content/uploads/2018/01/roma-colosseo.jpg" style="width:100%; height: 180px">
    <img class="card-img-top" src="http://www.ricardobofill.es/wp-content/uploads//2016/03/W_Barcelona_Hotel_Ricardo_Bofill_Taller_Arquitectura_Barcelona_Spain_01.jpg" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/commons/5/5e/Australia_Day.jpg" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://pix10.agoda.net/hotelImages/336/336870/336870_16042115000041680438.jpg?s=1024x768" alt="Card image" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://www.gannett-cdn.com/-mm-/1abbac059a7e6f21ff3aa7e38760a41a48819119/c=0-217-2118-1414/local/-/media/2018/04/14/USATODAY/USATODAY/636592630826477551-GettyImages-813272528.jpg?width=3200&height=1680&fit=crop" style="width:100%; height: 180px">
    <img class="card-img-top" src="https://www.worldtravelguide.net/wp-content/uploads/2017/09/shu-Europe-Spain-Madrid-Financial-district-245037493-Sean-Pavone-1440x823.jpg" style="width:100%; height: 180px">

-->

</div>

</div>

<%= render 'layouts/footer' %>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="text/javascript" src ="AP.js"></script>


</body>
</html>