config/routes.rb
Rails.application.routes.draw do
  get 'requests/new'

  get 'request/new'

  #get 'sessions/new'

  resources :users
  #get 'blogs/new'

  root 'initial_page#home'
  get '/home',  to: 'initial_page#home'
  get '/contact',  to: 'initial_page#contact'
  get '/admin',  to: 'initial_page#admin'
  #get '/post/:id',   to: 'blogs#post'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/admin', to: 'blogs#new'
  get   '/admin',   to: 'blogs#index'
  post    '/admin', to: 'blogs#create'
  get   '/request',  to: 'requests#new'
  post  '/request',  to: 'requests#create'
  delete '/requests/:id/edit', to: 'requests#destroy'
  delete '/blogs/:id/edit', to: 'blogs#destroy'
  #get   '/profile',  to: 'users#edit'
  #patch   '/profile', to: 'users#update'
  #get   '/blogs', to: 'blogs#index'

  resources :blogs
  resources :requests

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!--
#
# This is the HTML file for the footer, which is rendered in each other file
#
-->

<footer>

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  	<link href="https://fonts.googleapis.com/css?family=Cormorant|Cormorant+Infant:400,600|Cormorant+Upright|Roboto" rel="stylesheet">

<div id="footer">

	<hr class="style-four" style="width: 100%">

	<div class="container" style="margin-top: 3%; text-align: center;">

	<h1 id="link_contact" class="h2_about_us" style="margin-bottom: 25px;">Contact Us</h1>


	<div class="box_about_us_contact_us">
	 	<h5 style="margin-left: 55px;"><i style="position: absolute; margin-top: -10px;margin-left: -55px; color: slateblue; " class="fas fa-2x fa-phone-square"></i> (352) 538-4940</h5>
	</div>

	<div class="box_about_us_contact_us">
	 	<h5 style="margin-left: 55px;"><i style="position: absolute; margin-top: -10px;margin-left: -55px; color: slateblue" class="fas fa-2x fa-envelope-square"></i> info@bochitto.com</h5>
	</div>


	<div class="box_about_us_contact_us" >
	 	<h5 style="margin-left: 55px;"><i style="position: absolute; margin-top: -10px;margin-left: -55px; color: slateblue" class="fas fa-2x fa-map-marker-alt"></i> 686 Museum Rd, Gainesville, FL 32611</h5>
	</div>

	<div>
	<ul id="test" class="wrapper" style="display:list-item; float: none;">
		  <a href="http://www.google.com"><i class="fab fa-3x fa-instagram"></i></a>
		  <a href="https://www.facebook.com/Travelgal68/"><i class="fab fa-3x fa-facebook-square"></i></a>
		  <a href="http://www.twitter.com"><i class="fab fa-3x fa-twitter-square"></i></a>
	</ul>
</div>
	</div>



<hr class="style-four" style="width: 100%">


</footer>

app/views/layouts/_header.html.erb
<!--
#
# This is the HTML file for the header, which is rendered in each other file
#
-->

<header>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>

  .accountButton {
    background-color: lightblue;
    border-radius: 5px;
    color: navy;
    padding: 0px 5px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 0px 8px;
    -webkit-transition-duration: 0.3s; /* Safari */
    transition-duration: 0.3s;
    cursor: pointer;
  }
  .accountButton:hover {
    background-color: navy;
    color: white;
    box-shadow: 0 5px 5px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }
</style>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a><%= link_to image_tag("m.png",width: 140, alt: "Company logo"), root_path %></a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0" id="box-wrap">
        <li class="nav-item" id="box">
          <%= link_to "Home", root_path, id: "logo" %>
        </li>
        <li class="nav-item" id="box">
          <%= link_to "About Us", contact_path %>
        </li>
        <% if admin? %>
          <li class="nav-item" id="box">
            <%= link_to "Admin", admin_path %>
          </li>
        <% end %>
      </ul>
      <div>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0" id="box-wrap">
          <% if logged_in? %>
          <li class="nav-item" id="box" style="list-style-type: none;">
            <%= link_to "Your Requests", current_user %>
            <i style="margin-left: 5.5px;margin-right: 40px;"class="fas fa-user"></i>
          </li>
          <li class="nav-item" id="box" style="list-style-type: none;">
            <%= link_to "Settings", edit_user_path(current_user) %>
            <i style="margin-left: 5.5px;margin-right: 40px;"class="fas fa-user"></i>
          </li>
          <li class="nav-item" id="box" style="list-style-type: none;">
            <%= link_to "Log out", logout_path, method: :delete %>
            <i style="margin-left: 5.5px;" class="fas fa-sign-out-alt"></i>
          </li>
          <% else %>
          <li id="box" class="nav-item" style="list-style-type: none;">
            <%= link_to "Sign up", signup_path %>
            <i style="margin-left: 5.5px;" class="fas fa-user-plus"></i>
          </li>
          <li id="box" class="nav-item" style="list-style-type: none;">
            <%= link_to "Log in", login_path %>
            <i style="margin-left: 5.5px;margin-right: 40px;"class="fas fa-user"></i>
          </li>
          <% end %>
        </ul>
      </div>
<!--
      <% if logged_in? %>
      <button class="accountButton">
        <a class="form-inline my-2 my-lg-0" style="width: auto">
          <%= link_to "Log out", logout_path, method: :delete %>
        </a>
      </button>
      <% else %>

      <button class="accountButton">
        <a  class="form-inline my-2 my-lg-0" style="width: auto">
          <%= link_to "Sign up", signup_path, class: "sign_up" %>
          <i style="margin-left: 5.5px;" class="fas fa-user-plus"></i>
        </a>
      </button>

        <button class="accountButton">
        <a class="form-inline my-2 my-lg-0 button_cont" style="width: auto">
          <%= link_to "Log in", login_path, class: "sign_up" %>
          <i style="margin-left: 5.5px;margin-right: 40px;"class="fas fa-user"></i>
        </a>
      </button>
      <% end %>
-->

    </div>
  </nav>
</header>
<!--
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand">< %= link_to "TravelTeam3", root_path %></a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active">< %= link_to "Home", root_path, id: "logo" %></li>
        <li>< %= link_to "Contact", contact_path %></li>
        <li>< %= link_to "Admin", admin_path %></li>
      </ul>
    </div>
  </nav>
</header> -->
<!--<header class="ui secondary  menu">
  <a class="item">
    < %= link_to "Home", 'home' %>
  </a>
  <a class="item">
    < %= link_to "Contact", 'contact' %>
  </a>
  <a class="item">
    < %= link_to "Admin", 'admin' %>
  </a>
  <div class="right menu">
    <div class="item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
    <a class="ui item active">
      Logout
    </a>
  </div>
</header>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bochitto Travel</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "AP.css" %>
  </head>

  <body>
      <%= yield %>
      <script type="text/javascript" src ="app/assets/AP.js"></script>
  </body>
</html>